### ISSUE TITLE
One Way block not strong enough

### ISSUE THREAD

**Issue by tahg** [McJtyMods/restrictions#10]
When using Vanilla's boost key, you're strong/fast enough to push through the one way block the wrong way.  Can you add a way to prevent this?

**Comment by McJty** [comment]
I can make it configurable perhaps?

**Comment by tahg** [comment]
It looks like if you place them 2 high, that works (cause of stacking).  If you change the behavior based on issue #8, then a config would be nice, but for now it doesn't look like it's needed.

**Comment by McJty** [comment]
Ok
