### ISSUE TITLE
[1.14.4] Failed to load class mcjty.restrictions.Restrictions

### ISSUE THREAD

**Issue by Wynadorn** [McJtyMods/restrictions#12]
Hey McJtyMods,

I'd like to submit a crashlog for attempting to run 1.14-1.3.3-alpha on a fresh server.

Versions Used:
minecraft_server.1.14.4.jar
forge-1.14.4-28.1.1.jar
restrictions-1.14-1.3.3-alpha.jar

Crashlog:
https://pastebin.com/raw/H0efrmfb

**Comment by josephcsible** [comment]
What version of McJtyLib are you using?

**Comment by Wynadorn** [comment]
Oh, excuse me, I hadn't checked the Relations - Dependencies tab, I'm used to the mods having it in the Description. Thanks for your reply.
