### ISSUE TITLE
crash when teleporting away from an area with pushers

### ISSUE THREAD

**Issue by LlubNek** [McJtyMods/restrictions#17]
Minecraft 1.19.2
Forge 43.2.21
Restrictions 1.19-5.1.1

Teleporting away (waystones, ftb essentials /home, etc) from an area with pushers causes a crash (previously would freeze without any error message).

I'm playing a modified/updated ATM8.

[crash-2023-08-29_16.41.45-client.txt](https://github.com/McJtyMods/restrictions/files/12469341/crash-2023-08-29_16.41.45-client.txt)
[latest.log](https://github.com/McJtyMods/restrictions/files/12469349/latest.log)

**Comment by McJty** [comment]
I'll check it out soon. Thanks for reporting

**Comment by McJty** [comment]
Will be fixed next release
