### ISSUE TITLE
Feature request: way to be immune to this mod's blocks

### ISSUE THREAD

**Issue by josephcsible** [McJtyMods/restrictions#4]
While building with these blocks, it's annoying if you're constantly getting dragged by them yourself. Can we add some way to let you be immune to them? I know attractors and pushers can be turned off, but one-way blocks can't. My suggested proposal is glass boots, which would make the wearer unaffected by all 3 types of blocks.

**Comment by McJty** [comment]
Hmm nice idea

**Comment by McJty** [comment]
Implemented for next version

**Comment by McJty** [comment]
Implemented in next version
