### ISSUE TITLE
effect of Pusher/Attractor/One Way stack

### ISSUE THREAD

**Issue by tigerdan2** [McJtyMods/restrictions#8]
Place 4 Pusher/Attractor/One Waylike this
X X
X X

Stand in the middle, and you will get boosted way to hard

**Comment by McJty** [comment]
That's hard to avoid and is it really a problem?

**Comment by tigerdan2** [comment]
Yes it kinda is
for example
if you are moving from one oneway to another one you will gain extra speed while being in both
here are some other things that really shouldnt be possible
https://streamable.com/65ucd

**Comment by McJty** [comment]
Why shouldn't it be possible ? I don't get the problem

**Comment by Austin5003** [comment]
I'd say the effect stacking mechanic is actually quite useful
